kind = "web"
previewPath = "/"
title = "Omaox"
version = "1.0.0"
id = "artifacts/omaox"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25432

[services.development]
run = "pnpm --filter @workspace/omaox run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/omaox", "run", "build" ]
publicDir = "artifacts/omaox/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25432"
BASE_PATH = "/"
